[prune]
  non-go = true

# Pin to master branch until there is a more recent stable release:
#   https://github.com/prometheus/client_golang/issues/375
[[constraint]]
  name = "github.com/prometheus/client_golang"
  branch = "master"

# After aa801ca (v1.0.0), kuberesolver changed its API in a non-backwards
# compatible way. We need to pin this old version until we can refactor to the
# new API.
[[constraint]]
  name = "github.com/sercand/kuberesolver"
  version = "1.0.0"

# Older versions apparently have problems converting 'Any' types used in errors
[[constraint]]
  name = "github.com/gogo/googleapis"
  version = ">=v1.1.0"

# Need this version to get past https://github.com/gogo/status/issues/4
[[constraint]]
  name = "github.com/gogo/status"
  version = ">=v1.0.3"
